//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoCausa
    {
        public DocumentoCausa()
        {
            this.AsocCausaDocumento = new HashSet<AsocCausaDocumento>();
        }
    
        public int DocumentoCausaID { get; set; }
        public int CausaID { get; set; }
        public int VersionEncriptID { get; set; }
        public string Hash { get; set; }
        public string NombreArchivoFisico { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<AsocCausaDocumento> AsocCausaDocumento { get; set; }
        public virtual Causa Causa { get; set; }
        public virtual VersionEncript VersionEncript { get; set; }
    }
}
