//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoCausa
    {
        public EstadoCausa()
        {
            this.AsocTipoTramiteOpciones = new HashSet<AsocTipoTramiteOpciones>();
            this.Causa = new HashSet<Causa>();
            this.LogCausa = new HashSet<LogCausa>();
            this.EstadosAplica = new HashSet<EstadosAplica>();
        }

        public int EstadoCausaID { get; set; }
        public string Descripcion { get; set; }
        public bool Vigente { get; set; }

        public virtual ICollection<Causa> Causa { get; set; }
        public virtual ICollection<LogCausa> LogCausa { get; set; }
        public virtual ICollection<EstadosAplica> EstadosAplica { get; set; }
        public virtual ICollection<AsocTipoTramiteOpciones> AsocTipoTramiteOpciones { get; set; }
    }
}
