//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCausa
    {
        public int LogCausaID { get; set; }
        public int EstadoCausaID { get; set; }
        public int CausaID { get; set; }
        public System.DateTime Fecha { get; set; }
        public int UsuarioID { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Causa Causa { get; set; }
        public virtual EstadoCausa EstadoCausa { get; set; }
        
        //custom    
        public string Responsable { get; set; }

    }
}
