//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public Perfil()
        {
            this.AsocUsuarioPerfil = new HashSet<AsocUsuarioPerfil>();
            this.AsocTipoNotificacionPerfil = new HashSet<AsocTipoNotificacionPerfil>();
            this.AsocTipoCausaPerfil = new HashSet<AsocTipoCausaPerfil>();
        }
    
        public int PerfilID { get; set; }
        public string Descripcion { get; set; }
        public bool Vigente { get; set; }

        public virtual ICollection<AsocUsuarioPerfil> AsocUsuarioPerfil { get; set; }
        public virtual ICollection<AsocTipoNotificacionPerfil> AsocTipoNotificacionPerfil { get; set; }
        public virtual ICollection<AsocTipoCausaPerfil> AsocTipoCausaPerfil { get; set; }
    }
}
