//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTramite
    {
        public TipoTramite()
        {
            this.AsocTipoTramiteOpciones = new HashSet<AsocTipoTramiteOpciones>();
            this.Expediente = new HashSet<Expediente>();
        }
    
        public int TipoTramiteID { get; set; }
        public string Descripcion { get; set; }
        public bool Vigente { get; set; }
    
        public virtual ICollection<AsocTipoTramiteOpciones> AsocTipoTramiteOpciones { get; set; }
        public virtual ICollection<Expediente> Expediente { get; set; }
    }
}
