//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumento
    {
        public TipoDocumento()
        {
            this.AsocTipoDocumentoAdjunto = new HashSet<AsocTipoDocumentoAdjunto>();
            this.DocumentoSistema = new HashSet<DocumentoSistema>();
            this.DocumentoTmp = new HashSet<DocumentoTmp>();
        }

        public int TipoDocumentoID { get; set; }
        public string Descripcion { get; set; }
        public string Etiqueta { get; set; }
        public bool Visible { get; set; }
        public bool Obligatorio { get; set; }
        public int Cantidad { get; set; }
        public bool Vigente { get; set; }

        public virtual ICollection<AsocTipoDocumentoAdjunto> AsocTipoDocumentoAdjunto { get; set; }
        public virtual ICollection<DocumentoSistema> DocumentoSistema { get; set; }
        public virtual ICollection<DocumentoTmp> DocumentoTmp { get; set; }
    }
}
