//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionEncript
    {
        public VersionEncript()
        {
            this.DocumentoAdjunto = new HashSet<DocumentoAdjunto>();
            this.DocumentoCausa = new HashSet<DocumentoCausa>();
            this.DocumentoSistema = new HashSet<DocumentoSistema>();
            this.DocumentoTmp = new HashSet<DocumentoTmp>();
        }
    
        public int VersionEncriptID { get; set; }
        public string Cadena { get; set; }
    
        public virtual ICollection<DocumentoAdjunto> DocumentoAdjunto { get; set; }
        public virtual ICollection<DocumentoCausa> DocumentoCausa { get; set; }
        public virtual ICollection<DocumentoTmp> DocumentoTmp { get; set; }
        public virtual ICollection<DocumentoSistema> DocumentoSistema { get; set; }
    }
}
