
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class AsocEscritoDocto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AsocEscritoDocto()
    {

        this.AsocFirmaDocto = new HashSet<AsocFirmaDocto>();

    }


    public int AsocEscritoDoctoID { get; set; }

    public int AsocCausaDocumentoID { get; set; }

    public int ExpedienteID { get; set; }

    public Nullable<int> OpcionesTramiteID { get; set; }



    public virtual AsocCausaDocumento AsocCausaDocumento { get; set; }

    public virtual Expediente Expediente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsocFirmaDocto> AsocFirmaDocto { get; set; }

    public virtual OpcionesTramite OpcionesTramite { get; set; }

}

}
