//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsocTipoTramiteOpciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsocTipoTramiteOpciones()
        {
            this.EstadosAplica = new HashSet<EstadosAplica>();
        }
    
        public int AsocTipoTramiteOpcionesID { get; set; }
        public int TipoTramiteID { get; set; }
        public int OpcionesTramiteID { get; set; }
        public bool IsTabla { get; set; }
        public int PlazoDias { get; set; }
        public bool IsDiasHabiles { get; set; }
        public bool IsPermiteFechaAnterior { get; set; }
        public bool IsInformaAtraso { get; set; }
        public int NumeroFirmas { get; set; }
        public int Status1 { get; set; }
        public int Status2 { get; set; }
        public bool IsFinalizaIngreso { get; set; }
        public Nullable<int> EstadoCausaID { get; set; }
        public bool Vigente { get; set; }
    
        public virtual OpcionesTramite OpcionesTramite { get; set; }
        public virtual TipoTramite TipoTramite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadosAplica> EstadosAplica { get; set; }
        public virtual EstadoCausa EstadoCausa { get; set; }
    }
}
