
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class AsocDocSistemaFirma
{

    public int AsocDocSistemaFirmaID { get; set; }

    public int DocumentoSistemaID { get; set; }

    public int FirmaID { get; set; }

    public bool IsFirmado { get; set; }



    public virtual Firma Firma { get; set; }

    public virtual DocumentoSistema DocumentoSistema { get; set; }

}

}
