
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class AsocExpeFirma
{

    public int AsocExpeFirmaID { get; set; }

    public int FirmaID { get; set; }

    public int ExpedienteID { get; set; }



    public virtual Expediente Expediente { get; set; }

    public virtual Firma Firma { get; set; }

}

}
