
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class Causa
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Causa()
    {

        this.DocumentoCausa = new HashSet<DocumentoCausa>();

        this.LogCausa = new HashSet<LogCausa>();

        this.Parte = new HashSet<Parte>();

        this.Expediente = new HashSet<Expediente>();

        this.DetalleTabla = new HashSet<DetalleTabla>();

    }


    public int CausaID { get; set; }

    public int TipoCanalID { get; set; }

    public int EstadoCausaID { get; set; }

    public int UsuarioID { get; set; }

    public int UsuarioResponsableID { get; set; }

    public int TipoContenciosoID { get; set; }

    public int TipoCausaID { get; set; }

    public System.DateTime FechaIngreso { get; set; }

    public string NumeroTicket { get; set; }

    public string Numero { get; set; }

    public int Anio { get; set; }

    public string Denominacion { get; set; }

    public string Observacion { get; set; }

    public bool IsContencioso { get; set; }

    public string NumeroRegistro { get; set; }



    public virtual TipoCausa TipoCausa { get; set; }

    public virtual TipoContencioso TipoContencioso { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DocumentoCausa> DocumentoCausa { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LogCausa> LogCausa { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Parte> Parte { get; set; }

    public virtual EstadoCausa EstadoCausa { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Expediente> Expediente { get; set; }

    public virtual TipoCanal TipoCanal { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleTabla> DetalleTabla { get; set; }

    public virtual Usuario Usuario { get; set; }

}

}
