
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class Derivacion
{

    public int DerivacionID { get; set; }

    public int ExpedienteID { get; set; }

    public int UsuarioID { get; set; }

    public int UsuarioResponsableID { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public string Observacion { get; set; }

    public int PlazoDias { get; set; }



    public virtual Expediente Expediente { get; set; }

    public virtual Usuario Usuario { get; set; }

}

}
