
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class DocumentoSistema
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DocumentoSistema()
    {

        this.AsocDocSistemaFirma = new HashSet<AsocDocSistemaFirma>();

        this.AsocDocumentoSistemaEstadoDiario = new HashSet<AsocDocumentoSistemaEstadoDiario>();

        this.AsocDocumentoSistemaTabla = new HashSet<AsocDocumentoSistemaTabla>();

        this.AsocDocumentoUsuario = new HashSet<AsocDocumentoUsuario>();

    }


    public int DocumentoSistemaID { get; set; }

    public int VersionEncriptID { get; set; }

    public int TipoDocumentoID { get; set; }

    public string Hash { get; set; }

    public string NombreArchivoFisico { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public string Descripcion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsocDocSistemaFirma> AsocDocSistemaFirma { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsocDocumentoSistemaEstadoDiario> AsocDocumentoSistemaEstadoDiario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsocDocumentoSistemaTabla> AsocDocumentoSistemaTabla { get; set; }

    public virtual TipoDocumento TipoDocumento { get; set; }

    public virtual VersionEncript VersionEncript { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsocDocumentoUsuario> AsocDocumentoUsuario { get; set; }

}

}
