//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoAdjunto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentoAdjunto()
        {
            this.AsocCausaDocumento = new HashSet<AsocCausaDocumento>();
            this.AsocTipoDocumentoAdjunto = new HashSet<AsocTipoDocumentoAdjunto>();
        }
    
        public int DocumentoAdjuntoID { get; set; }
        public int VersionEncriptID { get; set; }
        public int MaximoTamanoArchivoID { get; set; }
        public int TipoFormatoID { get; set; }
        public string NombreDocumento { get; set; }
        public string Descripcion { get; set; }
        public string Hash { get; set; }
        public string NombreArchivoFisico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsocCausaDocumento> AsocCausaDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsocTipoDocumentoAdjunto> AsocTipoDocumentoAdjunto { get; set; }
        public virtual TipoFormato TipoFormato { get; set; }
        public virtual MaximoTamanoArchivo MaximoTamanoArchivo { get; set; }
        public virtual VersionEncript VersionEncript { get; set; }
    }
}
