
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class EstadosAplica
{

    public int EstadosAplicaID { get; set; }

    public int EstadoCausaID { get; set; }

    public int AsocTipoTramiteOpcionesID { get; set; }

    public bool IsSiguiente { get; set; }



    public virtual AsocTipoTramiteOpciones AsocTipoTramiteOpciones { get; set; }

    public virtual EstadoCausa EstadoCausa { get; set; }

}

}
