
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class Expediente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Expediente()
    {

        this.AsocEscritoDocto = new HashSet<AsocEscritoDocto>();

        this.AsocExpedienteOpcion = new HashSet<AsocExpedienteOpcion>();

        this.AsocExpeFirma = new HashSet<AsocExpeFirma>();

        this.Derivacion = new HashSet<Derivacion>();

        this.DetalleEstadoDiario = new HashSet<DetalleEstadoDiario>();

    }


    public int ExpedienteID { get; set; }

    public int TipoTramiteID { get; set; }

    public int CausaID { get; set; }

    public int UsuarioID { get; set; }

    public int UsuarioResponsableID { get; set; }

    public System.DateTime FechaIngreso { get; set; }

    public bool IsAdmisible { get; set; }

    public string Observacion { get; set; }

    public string Comentario { get; set; }

    public string NumeroOficio { get; set; }

    public int PlazoDias { get; set; }

    public bool IsHabil { get; set; }

    public bool IsTabla { get; set; }

    public bool IsFinalizado { get; set; }

    public Nullable<int> TablaID { get; set; }

    public int TipoCanalID { get; set; }

    public string NumeroTicket { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsocEscritoDocto> AsocEscritoDocto { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsocExpedienteOpcion> AsocExpedienteOpcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsocExpeFirma> AsocExpeFirma { get; set; }

    public virtual Causa Causa { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Derivacion> Derivacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleEstadoDiario> DetalleEstadoDiario { get; set; }

    public virtual TipoTramite TipoTramite { get; set; }

    public virtual Tabla Tabla { get; set; }

    public virtual TipoCanal TipoCanal { get; set; }

    public virtual Usuario Usuario { get; set; }

}

}
