
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class LogSistema
{

    public int LogSistemaID { get; set; }

    public System.DateTime Fecha { get; set; }

    public string Pagina { get; set; }

    public string Accion { get; set; }

    public Nullable<int> ExpedienteID { get; set; }

    public int UsuarioID { get; set; }

    public string Parametros { get; set; }

    public string IpUsuario { get; set; }

    public string Tipo { get; set; }

    public string Descripcion { get; set; }

}

}
