
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class Tabla
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tabla()
    {

        this.AsocDocumentoSistemaTabla = new HashSet<AsocDocumentoSistemaTabla>();

        this.DetalleTabla = new HashSet<DetalleTabla>();

        this.Expediente = new HashSet<Expediente>();

    }


    public int TablaID { get; set; }

    public int EstadoTablaID { get; set; }

    public int TipoTablaID { get; set; }

    public int SalaID { get; set; }

    public System.DateTime Fecha { get; set; }

    public int UsuarioRelatorID { get; set; }

    public int UsuarioSubroganteID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsocDocumentoSistemaTabla> AsocDocumentoSistemaTabla { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleTabla> DetalleTabla { get; set; }

    public virtual EstadoTabla EstadoTabla { get; set; }

    public virtual Sala Sala { get; set; }

    public virtual TipoTabla TipoTabla { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Expediente> Expediente { get; set; }

}

}
