
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class TempMigraAdjuntos
{

    public int TempID { get; set; }

    public int Identidad { get; set; }

    public int Tipo { get; set; }

    public int Anio { get; set; }

    public string RutaArchivo { get; set; }

    public string NombreArchivo { get; set; }

    public bool Migrado { get; set; }

    public string Comentario { get; set; }

}

}
