//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoDocumento()
        {
            this.AsocTipoDocumentoAdjunto = new HashSet<AsocTipoDocumentoAdjunto>();
            this.DocumentoSistema = new HashSet<DocumentoSistema>();
            this.DocumentoTmp = new HashSet<DocumentoTmp>();
        }
    
        public int TipoDocumentoID { get; set; }
        public string Descripcion { get; set; }
        public string Etiqueta { get; set; }
        public bool Visible { get; set; }
        public bool Obligatorio { get; set; }
        public int Cantidad { get; set; }
        public bool Vigente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsocTipoDocumentoAdjunto> AsocTipoDocumentoAdjunto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoSistema> DocumentoSistema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoTmp> DocumentoTmp { get; set; }
    }
}
