
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class TipoNotificacion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoNotificacion()
    {

        this.AsocTipoNotificacionPerfil = new HashSet<AsocTipoNotificacionPerfil>();

    }


    public int TipoNotificacionID { get; set; }

    public string Descripcion { get; set; }

    public string Asunto { get; set; }

    public bool Vigente { get; set; }

    public string Mensaje { get; set; }

    public string ConCopia { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsocTipoNotificacionPerfil> AsocTipoNotificacionPerfil { get; set; }

}

}
