
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistence.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class Ventana
{

    public int VentanaID { get; set; }

    public int TipoVentanaID { get; set; }

    public string IntroduccionEspanol { get; set; }

    public string IntroduccionIngles { get; set; }



    public virtual TipoVentana TipoVentana { get; set; }

}

}
