//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Administracion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Administracion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.Administracion", typeof(Administracion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar MimeType.
        /// </summary>
        public static string AgregarMimeType {
            get {
                return ResourceManager.GetString("AgregarMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string AgregarTipoFormato {
            get {
                return ResourceManager.GetString("AgregarTipoFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Campo.
        /// </summary>
        public static string CrearCampo {
            get {
                return ResourceManager.GetString("CrearCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe Seleccionar Descripción.
        /// </summary>
        public static string DebeSeleccionarDescripcion {
            get {
                return ResourceManager.GetString("DebeSeleccionarDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Mantenedor.
        /// </summary>
        public static string DescMantenedor {
            get {
                return ResourceManager.GetString("DescMantenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Campo.
        /// </summary>
        public static string EditarCampo {
            get {
                return ResourceManager.GetString("EditarCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar MimeType.
        /// </summary>
        public static string EditarMimeType {
            get {
                return ResourceManager.GetString("EditarMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Tipo de Formato.
        /// </summary>
        public static string EditarTipoFormato {
            get {
                return ResourceManager.GetString("EditarTipoFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CSS Adicional.
        /// </summary>
        public static string ExtraCSS {
            get {
                return ResourceManager.GetString("ExtraCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar Texto.
        /// </summary>
        public static string FiltrarTexto {
            get {
                return ResourceManager.GetString("FiltrarTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jefatura SIAC.
        /// </summary>
        public static string JefaturaSIAC {
            get {
                return ResourceManager.GetString("JefaturaSIAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jefatura Unidad.
        /// </summary>
        public static string JefaturaUnidad {
            get {
                return ResourceManager.GetString("JefaturaUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenedor de Ayudas.
        /// </summary>
        public static string MantenedorAyudas {
            get {
                return ResourceManager.GetString("MantenedorAyudas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenedor Genérico.
        /// </summary>
        public static string MantenedorGenerico {
            get {
                return ResourceManager.GetString("MantenedorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MimeType.
        /// </summary>
        public static string MimeType {
            get {
                return ResourceManager.GetString("MimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MimeTypes de.
        /// </summary>
        public static string MimeTypesDe {
            get {
                return ResourceManager.GetString("MimeTypesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenedor Genérico.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantillas de Email.
        /// </summary>
        public static string PlantillasEmail {
            get {
                return ResourceManager.GetString("PlantillasEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string Responsable {
            get {
                return ResourceManager.GetString("Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subrogante.
        /// </summary>
        public static string Subrogante {
            get {
                return ResourceManager.GetString("Subrogante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Ventana.
        /// </summary>
        public static string TipoVentana {
            get {
                return ResourceManager.GetString("TipoVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario SIAC.
        /// </summary>
        public static string UsuarioSIAC {
            get {
                return ResourceManager.GetString("UsuarioSIAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente.
        /// </summary>
        public static string Vigente {
            get {
                return ResourceManager.GetString("Vigente", resourceCulture);
            }
        }
    }
}
