//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración.
        /// </summary>
        public static string Administracion {
            get {
                return ResourceManager.GetString("Administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ambos.
        /// </summary>
        public static string Ambos {
            get {
                return ResourceManager.GetString("Ambos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre.
        /// </summary>
        public static string BrnCierre {
            get {
                return ResourceManager.GetString("BrnCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string BtnAceptar {
            get {
                return ResourceManager.GetString("BtnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string BtnActualizar {
            get {
                return ResourceManager.GetString("BtnActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string BtnAgregar {
            get {
                return ResourceManager.GetString("BtnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string BtnAprobar {
            get {
                return ResourceManager.GetString("BtnAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string BtnBorrar {
            get {
                return ResourceManager.GetString("BtnBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string BtnBuscar {
            get {
                return ResourceManager.GetString("BtnBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string BtnCancelar {
            get {
                return ResourceManager.GetString("BtnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string BtnDescargar {
            get {
                return ResourceManager.GetString("BtnDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devolver.
        /// </summary>
        public static string BtnDevolver {
            get {
                return ResourceManager.GetString("BtnDevolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string BtnEditar {
            get {
                return ResourceManager.GetString("BtnEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string BtnEliminar {
            get {
                return ResourceManager.GetString("BtnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string BtnEnviar {
            get {
                return ResourceManager.GetString("BtnEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string BtnGuardar {
            get {
                return ResourceManager.GetString("BtnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        public static string BtnImprimir {
            get {
                return ResourceManager.GetString("BtnImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string BtnLimpiar {
            get {
                return ResourceManager.GetString("BtnLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string BtnNuevo {
            get {
                return ResourceManager.GetString("BtnNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string BtnRechazar {
            get {
                return ResourceManager.GetString("BtnRechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string BtnVer {
            get {
                return ResourceManager.GetString("BtnVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver/Editar.
        /// </summary>
        public static string BtnVerEditar {
            get {
                return ResourceManager.GetString("BtnVerEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string BtnVolver {
            get {
                return ResourceManager.GetString("BtnVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda.
        /// </summary>
        public static string Busqueda {
            get {
                return ResourceManager.GetString("Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutar Carga de Datos.
        /// </summary>
        public static string CargaDatos {
            get {
                return ResourceManager.GetString("CargaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colapsar todo.
        /// </summary>
        public static string ColapsarTodo {
            get {
                return ResourceManager.GetString("ColapsarTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Confirma Eliminar el registro?.
        /// </summary>
        public static string ConfirmaEliminar {
            get {
                return ResourceManager.GetString("ConfirmaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        public static string Copiar {
            get {
                return ResourceManager.GetString("Copiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan %d días, %h horas, %i minutos y %s segundos para el término del plazo..
        /// </summary>
        public static string CountDownTemplate {
            get {
                return ResourceManager.GetString("CountDownTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos han sido guardados correctamente.
        /// </summary>
        public static string DatosGuardadosCorrectamente {
            get {
                return ResourceManager.GetString("DatosGuardadosCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una opción.
        /// </summary>
        public static string DebeSeleccionarUnaOpcion {
            get {
                return ResourceManager.GetString("DebeSeleccionarUnaOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación fallida.
        /// </summary>
        public static string ErrorMSG {
            get {
                return ResourceManager.GetString("ErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha de Término debe ser mayor a la de Inicio.
        /// </summary>
        public static string errorMsgFecha {
            get {
                return ResourceManager.GetString("errorMsgFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expandir todo.
        /// </summary>
        public static string ExpandirTodo {
            get {
                return ResourceManager.GetString("ExpandirTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extensiones Permitidas.
        /// </summary>
        public static string ExtensionesPermitidas {
            get {
                return ResourceManager.GetString("ExtensionesPermitidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        public static string Filtros {
            get {
                return ResourceManager.GetString("Filtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        public static string Finalizar {
            get {
                return ResourceManager.GetString("Finalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        public static string Generar {
            get {
                return ResourceManager.GetString("Generar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string GridBtnAnterior {
            get {
                return ResourceManager.GetString("GridBtnAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string GridBtnSiguiente {
            get {
                return ResourceManager.GetString("GridBtnSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string GridIrPrimerRegistro {
            get {
                return ResourceManager.GetString("GridIrPrimerRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay resultados.
        /// </summary>
        public static string GridSinResultados {
            get {
                return ResourceManager.GetString("GridSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin.
        /// </summary>
        public static string GridUltimoRegistro {
            get {
                return ResourceManager.GetString("GridUltimoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error.
        /// </summary>
        public static string HaOcurridoError {
            get {
                return ResourceManager.GetString("HaOcurridoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string IdiomaEN {
            get {
                return ResourceManager.GetString("IdiomaEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string IdiomaES {
            get {
                return ResourceManager.GetString("IdiomaES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string LabelDescargar {
            get {
                return ResourceManager.GetString("LabelDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ambos.
        /// </summary>
        public static string LabelIdiomaAmbos {
            get {
                return ResourceManager.GetString("LabelIdiomaAmbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string LabelIdiomaEN {
            get {
                return ResourceManager.GetString("LabelIdiomaEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string LabelIdiomaES {
            get {
                return ResourceManager.GetString("LabelIdiomaES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desmarcar todos.
        /// </summary>
        public static string labelMarcarNada {
            get {
                return ResourceManager.GetString("labelMarcarNada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check all.
        /// </summary>
        public static string labelMarcarTodo {
            get {
                return ResourceManager.GetString("labelMarcarTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Vigente.
        /// </summary>
        public static string LabelNoVigente {
            get {
                return ResourceManager.GetString("LabelNoVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección....
        /// </summary>
        public static string LabelOptionInicial {
            get {
                return ResourceManager.GetString("LabelOptionInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección Filtro....
        /// </summary>
        public static string LabelOptionInicialFiltro {
            get {
                return ResourceManager.GetString("LabelOptionInicialFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente.
        /// </summary>
        public static string LabelVigente {
            get {
                return ResourceManager.GetString("LabelVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string Limpiar {
            get {
                return ResourceManager.GetString("Limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenedor de Feriados.
        /// </summary>
        public static string MantenedorDiasFeriados {
            get {
                return ResourceManager.GetString("MantenedorDiasFeriados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desmarcar todos.
        /// </summary>
        public static string MarcarNada {
            get {
                return ResourceManager.GetString("MarcarNada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcar todos.
        /// </summary>
        public static string MarcarTodo {
            get {
                return ResourceManager.GetString("MarcarTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede indicar más de un correo, para ello sepárelos mediante un coma.
        /// </summary>
        public static string MasDeUnCorreo {
            get {
                return ResourceManager.GetString("MasDeUnCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error. Contacte al Administrador.
        /// </summary>
        public static string MSGGeneralError {
            get {
                return ResourceManager.GetString("MSGGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Vigente.
        /// </summary>
        public static string NoVigente {
            get {
                return ResourceManager.GetString("NoVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación realizada.
        /// </summary>
        public static string OperacionRealizada {
            get {
                return ResourceManager.GetString("OperacionRealizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección....
        /// </summary>
        public static string OptionInicial {
            get {
                return ResourceManager.GetString("OptionInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Filtro....
        /// </summary>
        public static string OptionInicialFiltro {
            get {
                return ResourceManager.GetString("OptionInicialFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plazo finalizado.
        /// </summary>
        public static string PlazoFinalizado {
            get {
                return ResourceManager.GetString("PlazoFinalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preparar para Exportar.
        /// </summary>
        public static string PrepararExportar {
            get {
                return ResourceManager.GetString("PrepararExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro ha sido eliminado.
        /// </summary>
        public static string RegistroEliminado {
            get {
                return ResourceManager.GetString("RegistroEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a registros por pág.
        /// </summary>
        public static string RegPorPag {
            get {
                return ResourceManager.GetString("RegPorPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string Reportes {
            get {
                return ResourceManager.GetString("Reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reservas Realizadas.
        /// </summary>
        public static string ReservasRealizadas {
            get {
                return ResourceManager.GetString("ReservasRealizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados.
        /// </summary>
        public static string Resultados {
            get {
                return ResourceManager.GetString("Resultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron resultados.
        /// </summary>
        public static string SearchResult_NoMatch {
            get {
                return ResourceManager.GetString("SearchResult_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin.
        /// </summary>
        public static string SearchResult_PagerEnd {
            get {
                return ResourceManager.GetString("SearchResult_PagerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Todo.
        /// </summary>
        public static string SeleccionarTodo {
            get {
                return ResourceManager.GetString("SeleccionarTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin información.
        /// </summary>
        public static string SinInformacion {
            get {
                return ResourceManager.GetString("SinInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes Generales.
        /// </summary>
        public static string SolicitudesGenerales {
            get {
                return ResourceManager.GetString("SolicitudesGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Archivo.
        /// </summary>
        public static string SubirArchivo {
            get {
                return ResourceManager.GetString("SubirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODULO DE GESTIÓN DE EXPEDIENTES - SGDE.
        /// </summary>
        public static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto Inglés.
        /// </summary>
        public static string TextoENG {
            get {
                return ResourceManager.GetString("TextoENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto Español.
        /// </summary>
        public static string TextoESP {
            get {
                return ResourceManager.GetString("TextoESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string TH_Acciones {
            get {
                return ResourceManager.GetString("TH_Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #.
        /// </summary>
        public static string TH_Number {
            get {
                return ResourceManager.GetString("TH_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TDPI.
        /// </summary>
        public static string TituloCliente {
            get {
                return ResourceManager.GetString("TituloCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODULO DE GESTIÓN DE EXPEDIENTES - SGDE.
        /// </summary>
        public static string TituloSistema {
            get {
                return ResourceManager.GetString("TituloSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Inglés.
        /// </summary>
        public static string ToolTip_EN {
            get {
                return ResourceManager.GetString("ToolTip_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Español.
        /// </summary>
        public static string ToolTip_ES {
            get {
                return ResourceManager.GetString("ToolTip_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Detalle.
        /// </summary>
        public static string VerDetalle {
            get {
                return ResourceManager.GetString("VerDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente.
        /// </summary>
        public static string Vigente {
            get {
                return ResourceManager.GetString("Vigente", resourceCulture);
            }
        }
    }
}
