//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UploadFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadFiles() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.UploadFiles", typeof(UploadFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjunto.
        /// </summary>
        public static string Adjunto {
            get {
                return ResourceManager.GetString("Adjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga de Archivos.
        /// </summary>
        public static string CargaArchivos {
            get {
                return ResourceManager.GetString("CargaArchivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga de Archivo.
        /// </summary>
        public static string CargaDeArchivo {
            get {
                return ResourceManager.GetString("CargaDeArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        public static string Cargando {
            get {
                return ResourceManager.GetString("Cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cédula Indentidad.
        /// </summary>
        public static string CedulaIndentidad {
            get {
                return ResourceManager.GetString("CedulaIndentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currículum Vitae.
        /// </summary>
        public static string CurriculumVitae {
            get {
                return ResourceManager.GetString("CurriculumVitae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Confirma eliminar el Archivo?.
        /// </summary>
        public static string dialogEliminar {
            get {
                return ResourceManager.GetString("dialogEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos de antecedentes académicos.
        /// </summary>
        public static string DocAntAca {
            get {
                return ResourceManager.GetString("DocAntAca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descarga de Archivo.
        /// </summary>
        public static string Error_Descarga {
            get {
                return ResourceManager.GetString("Error_Descarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento.
        /// </summary>
        public static string Error_ElDocumento {
            get {
                return ResourceManager.GetString("Error_ElDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la Descarga!.
        /// </summary>
        public static string Error_EnLaDescarga {
            get {
                return ResourceManager.GetString("Error_EnLaDescarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no ha podido descargarse, puede que el archivo no exista o los parámetros de entrada sean incorrectos..
        /// </summary>
        public static string Error_NoHaPosisoDescargarse {
            get {
                return ResourceManager.GetString("Error_NoHaPosisoDescargarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Consultor.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string FileInput_buttonText {
            get {
                return ResourceManager.GetString("FileInput_buttonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string FileInput_changeText {
            get {
                return ResourceManager.GetString("FileInput_changeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección de archivo.
        /// </summary>
        public static string FileInput_inputText {
            get {
                return ResourceManager.GetString("FileInput_inputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga de archivo.
        /// </summary>
        public static string help_lblArchivo {
            get {
                return ResourceManager.GetString("help_lblArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede anexar otros archivos que usted considere relevantes..
        /// </summary>
        public static string help_OtrosArchivos {
            get {
                return ResourceManager.GetString("help_OtrosArchivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el archivo que necesita cargar a la plataforma y presione el botón “Subir Archivo”..
        /// </summary>
        public static string help_SubirArchivo {
            get {
                return ResourceManager.GetString("help_SubirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        public static string lblArchivo {
            get {
                return ResourceManager.GetString("lblArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string lblDescripcion {
            get {
                return ResourceManager.GetString("lblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extensiones permitidas.
        /// </summary>
        public static string lblExtensiones {
            get {
                return ResourceManager.GetString("lblExtensiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Archivo.
        /// </summary>
        public static string lblSubirArchivo {
            get {
                return ResourceManager.GetString("lblSubirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando.
        /// </summary>
        public static string messageCargando {
            get {
                return ResourceManager.GetString("messageCargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la carga.
        /// </summary>
        public static string messageErrorCarga {
            get {
                return ResourceManager.GetString("messageErrorCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar una Descripción.
        /// </summary>
        public static string messageErrorDescripcion {
            get {
                return ResourceManager.GetString("messageErrorDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un archivo.
        /// </summary>
        public static string messageErrorSelect {
            get {
                return ResourceManager.GetString("messageErrorSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un Tipo de Proceso.
        /// </summary>
        public static string messageErrorTP {
            get {
                return ResourceManager.GetString("messageErrorTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo está vacío.
        /// </summary>
        public static string messageErrorVacio {
            get {
                return ResourceManager.GetString("messageErrorVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo ha sido eliminado.
        /// </summary>
        public static string messageSuccess {
            get {
                return ResourceManager.GetString("messageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo ya fue cargado anteriormente.
        /// </summary>
        public static string msg_ArchivoYaFueCargado {
            get {
                return ResourceManager.GetString("msg_ArchivoYaFueCargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato reemplazado manualmente.
        /// </summary>
        public static string msg_ContratoReemplazado {
            get {
                return ResourceManager.GetString("msg_ContratoReemplazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato reemplazado manualmente, posterior al envío al consultor.
        /// </summary>
        public static string msg_ContratoReemplazadoManualmente {
            get {
                return ResourceManager.GetString("msg_ContratoReemplazadoManualmente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la carga del archivo.
        /// </summary>
        public static string msg_ErrorCargaArchivo {
            get {
                return ResourceManager.GetString("msg_ErrorCargaArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de archivo no soportado..
        /// </summary>
        public static string msg_FormatoNoSoportado {
            get {
                return ResourceManager.GetString("msg_FormatoNoSoportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del archivo no debe superar los {0} caracteres..
        /// </summary>
        public static string msg_MaximoCaracteres {
            get {
                return ResourceManager.GetString("msg_MaximoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se logró almacenar el archivo..
        /// </summary>
        public static string msg_NoAlmacenarArchivo {
            get {
                return ResourceManager.GetString("msg_NoAlmacenarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Archivo demasiado largo, intente con un nombre más corto..
        /// </summary>
        public static string msg_NombreArchivoDemasiadoLargo {
            get {
                return ResourceManager.GetString("msg_NombreArchivoDemasiadoLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo no se ha podido guardar en el directorio.
        /// </summary>
        public static string msg_NoSeGuardoElArchivo {
            get {
                return ResourceManager.GetString("msg_NoSeGuardoElArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error, no fue posible procesar el documento..
        /// </summary>
        public static string msg_NoSePudoProcesarDocumento {
            get {
                return ResourceManager.GetString("msg_NoSePudoProcesarDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problemas con el archivo, no se puede acceder al contenido, intente almarcenar el archivo con una versión mas reciente..
        /// </summary>
        public static string msg_ProblemasConElArchivo {
            get {
                return ResourceManager.GetString("msg_ProblemasConElArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo supera el tamaño máximo permitido..
        /// </summary>
        public static string msg_TamanioMaximo {
            get {
                return ResourceManager.GetString("msg_TamanioMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros Archivos.
        /// </summary>
        public static string OtrosArchivos {
            get {
                return ResourceManager.GetString("OtrosArchivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Archivo.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reemplazar Archivo.
        /// </summary>
        public static string ReemplazarArchivo {
            get {
                return ResourceManager.GetString("ReemplazarArchivo", resourceCulture);
            }
        }
    }
}
